CREATE TABLE Players(
    ID INTEGER, 
    playerID VARCHAR(50),
    yearID INTEGER,
    stint INTEGER,
    teamID VARCHAR(10),
    lgID VARCHAR(10),
    G INTEGER,
    AB REAL,
    R REAL,
    H REAL,
    "2B" REAL,
    "3B" REAL,
    HR REAL,
    RBI REAL,
    SB REAL,
    CS REAL,
    BB REAL,
    SO REAL,
    IBB REAL,
    HBP REAL,
    SH REAL,
    SF REAL,
    GIDP REAL,
    AVG REAL,
    PA REAL,
    OBP REAL,
    "1B" REAL,
    TB REAL,
    SLG REAL,
    OPS REAL,
    PRIMARY KEY (ID)
);